name: news_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.13.5
  cached_network_image: ^3.2.2
  webview_flutter: ^3.0.4
  share: ^2.0.4
  animated_splash_screen: ^1.0.1+2
  shared_preferences: ^2.0.15
  swipedetector: ^1.2.0
  provider:
  font_awesome_flutter:
  date_format: ^2.0.7
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true